name: tabsplanation

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python>=3.10,<3.12
  - pip >=21.1
  - setuptools_scm
  - toml

  # Package dependencies
  - pytask>=0.2.6,<0.3.0
  - numpy>=1.23.3,<2.0.0
  - matplotlib==3.5
  - pandas>=1.5.0,<2.0.0
  - ipykernel>=6.16.0,<7.0.0
  - tomli>=2.0.1,<3.0.0
  - pytorch-lightning==1.8.1
  - omegaconf>=2.2.3,<3.0.0
  - scikit-learn>=1.2.0,<2.0.0
  - nomkl # To solve a weird issue: https://github.com/dmlc/xgboost/issues/1715

  # Reproducibility
  - conda-lock

  # Misc
  - black
  - ipython
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
  - tox-conda

  # Documentation
  - furo
  - myst-parser
  - nbsphinx
  - sphinx
  - sphinx-autoapi
  - sphinx-copybutton
  - sphinx-panels

  - pip:
    - -e .
    - sphinxext-opengraph
