seed: 42
load_autoencoders_from: false # Or a relative path like "2022-30-10/18-35-30"
load_classifiers_from: false # Or a relative path like "2022-30-10/18-35-30"
dataset:
  dir: "data/cake_on_sea/uniform" # Should work if script is run from root dir
  input_dim: 250 # All of them
plots:
  show: false
  save: true
training:
  patience: 5
classifier:
  models:
    - Classifier
  args:
    hidden_dims: [50, 25]
autoencoder:
  models:
    - AE
    - VAE
    - VAENormalized
  args:
    input_dim: ${dataset.input_dim}
    learning_rate: 0.001
    latent_dim: 3
    hidden_dim: 128
    kl_factor: 1.0
    # These are arguments for NICE
    mlp_hidden_dims: [50, 50, 50, 50, 50]
    batch_norm: false
    dropout: null
  training:
    validation_data_proportion: 0.2
    test_data_proportion: 0.2
    batch_size: 200
    learning_rate: 0.001
    max_epochs: -1
