seed: 42
data:
  seed: ${seed}
  gaussian: false
  nb_points_initial: 100000
  nb_dims: 2
  nb_uncorrelated_dims: 2
data_module:
  validation_data_proportion: 0.2
  test_data_proportion: 0.2
  batch_size: 200
  correct_for_class_imbalance: false
training:
  patience: 5
  max_epochs: -1
classifier:
  seed: ${seed}
  data: ${data}
  data_module: ${data_module}
  training: ${training}
  model:
    # The name of the class, must be exported by `tabsplanation.models`
    class_name: Classifier
    args:
      output_dim: 3
      hidden_dims: [50, 50]
      batch_norm: False
      dropout: null
      learning_rate: 1e-3
autoencoder:
  seed: ${seed}
  data: ${data}
  data_module: ${data_module}
  training: ${training}
  model:
    class_name: NICEModel
    args:
      # Go get the input dim from autoencoder.data
      input_dim: ${...data.nb_dims}
      mlp_hidden_dims: [50, 50, 50, 50]
      batch_norm: False
      dropout: null
      learning_rate: 1e-3
# Plot data config
lo: -5
hi: 5
nb_steps: 25
