seed: 42
data:
  seed: ${seed}
  gaussian: false
  nb_points_initial: 100000
  nb_dims: 2
  nb_uncorrelated_dims: 2
data_module:
  validation_data_proportion: 0.2
  test_data_proportion: 0.2
  batch_size: 200
  correct_for_class_imbalance: false
training:
  patience: 5
  max_epochs: -1
path_regularized_model:
  seed: ${seed}
  data: ${data}
  data_module: ${data_module}
  training: ${training}
  training:
    patience: 5
    max_epochs: -1
  class_name: PathRegularizedNICE
  args:
    classifier:
      seed: ${seed}
      data: ${data}
      data_module: ${data_module}
      training:
        patience: 5
        max_epochs: -1
      model:
        class_name: Classifier
        args:
          output_dim: 3
          hidden_dims: [50, 50]
          batch_norm: False
          dropout: null
          learning_rate: 1e-3
    explainer:
      class_name: LatentShift
      args:
        hparams:
          max_iter: 100
          shift_step: 0.1
    autoencoder_args:
      # Go get the input dim from autoencoder.data
      input_dim: ${path_regularized_model.data.nb_dims}
      mlp_hidden_dims: [50, 50, 50, 50]
      batch_norm: False
      dropout: null
      learning_rate: 1e-3
