seed: 42
nb_seeds: 0

training:
  patience: 5
  max_epochs: -1

data_module_args:
  validation_data_proportion: 0.2
  test_data_proportion: 0.2
  batch_size: 200
  correct_for_class_imbalance: false

data_modules:
- seed: ${seed}
  args: ${data_module_args}
  dataset:
    class_name: tabsplanation.data.CakeOnSeaDataset
    args: 
      seed: ${seed}
      gaussian: false
      nb_points_initial: 100000
      nb_dims: 2
      nb_uncorrelated_dims: 2
- seed: ${seed}
  args: 
    batch_size: 1000
    validation_data_proportion: ${data_module_args.validation_data_proportion}
    test_data_proportion: ${data_module_args.test_data_proportion}
    correct_for_class_imbalance: ${data_module_args.correct_for_class_imbalance}
  dataset:
    class_name: tabsplanation.data.ForestCoverDataset
    args: null

classifier:
  seed: ${seed}
  data_module: null
  training: ${training}
  model:
    class_name: Classifier
    args:
      # output_dim: 3
      hidden_dims: [50, 50]
      batch_norm: False
      dropout: null
      learning_rate: 1e-3


autoencoder:
  seed: null
  data_module: null
  training: ${training}
  model:
    class_name: NICEModel
    args:
      input_dim: null
      mlp_hidden_dims: [50, 50, 50, 50]
      batch_norm: False
      dropout: null
      learning_rate: 1e-3

explainers:
- class_name: tabsplanation.explanations.LatentShift
  args:
    hparams:
      max_iter: 50
      shift_step: 0.1
- class_name: tabsplanation.explanations.Revise
  args:
    hparams:
      max_iter: 50
      lr: 1e-3
      distance_regularization: 0

losses:
- tabsplanation.explanations.losses.AwayLoss
- tabsplanation.explanations.losses.TargetLoss
- tabsplanation.explanations.losses.BinaryStretchLoss
- tabsplanation.explanations.losses.StretchLoss
